title: Memorandum
<<<<<<< HEAD
#email: nauoneu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  このサイトは個人的な備忘録としてITに関する主に技術的な情報を記録しているものです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: jekyll-theme-minimal
#theme: minima
plugins:
  - jekyll-feed
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
description: Something about Information Technology
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
>>>>>>> 35142b0d2cef5bec64a332c358a0ca27c26290f0
